### PR TITLE
H to ZZ now using atlasopenmagic

### PR DESCRIPTION
**Pull request by eirikgr**
The main change is that the notebook now uses the atlasopenmagic package to access the ntuples directly. 

I've done some cosmetic changes to the notebook too, but nothing controversial.

### CODE REVIEW

**Comment by zlmarshall** [comment]
Thanks @eirikgr ! Stupid general question: I think we wanted to rename some of these notebooks to get rid of the 'new' part of the name? 

I'm kinda selfishly wondering if you push changes on top of the notebook without 'New' in the name, if we'll then see real differences in the notebook and not just have a new notebook to review :)

Thanks again,
Zach

**Comment by eirikgr** [comment]
> I'm kinda selfishly wondering if you push changes on top of the notebook without 'New' in the name, if we'll then see real differences in the notebook and not just have a new notebook to review :)
> 
Good idea. Had a try at this [here](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/compare/HtoZZ-for-beta-rel), but the diff is still huge so not sure it helps much...

Eirik

**Review by zlmarshall — COMMENTED** [review]
This is a really nice update, thanks @eirikgr ! Just a couple of comments, some rather picky.

Best,
Zach

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb [hunk 1]
```diff
@@ -0,0 +1,1582 @@
...
+  },
+  {
+   "cell_type": "markdown",
+   "metadata": {},
+   "source": [
+    "### What is the Higgs boson? \n",
+    "The Higgs boson is a fundamental particle predicted by the Standard Model. \n",
+    "It is a manifestation of the Higgs field,\n",
+    "    which gives mass to the fundamental particles.\n",
+    "However,\n",
```
[the remark this answers is not in the document]
Comment (marianaiv) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:49]: This is how Henxiang wrote the notebook. I'm guessing it was more comfortable in the text editor. I don't remember this looking different in the notebook though. I think markdown doesn't pay attention to single-line breaks

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb [hunk 2]
```diff
@@ -0,0 +1,1582 @@
...
+   "execution_count": 1,
+   "metadata": {},
+   "outputs": [],
+   "source": [
+    "import sys\n",
+    "import os.path\n",
+    "# update the pip package installer\n",
+    "# !{sys.executable} -m pip install --upgrade --user pip\n",
+    "# install required packages\n",
+    "# !{sys.executable} -m pip install --upgrade --user uproot awkward vector numpy matplotlib"
```
[the remark this answers is not in the document]
Comment (marianaiv) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:197]: Well, either list the libraries or just leave it without an argument (it installs by default the env in the notebooks repository). I would go for:
```
install_from_environment()
```

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb (hunk 1 above)
[the remark this answers is not in the document]
Comment (zlmarshall) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:49]: Ok, a bit of a relief then... and I take it back :)

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb [hunk 3]
```diff
@@ -0,0 +1,1582 @@
...
+   "cell_type": "markdown",
+   "metadata": {},
+   "source": [
+    "## How to rediscover the Higgs boson yourself!"
+   ]
+  },
+  {
+   "cell_type": "markdown",
+   "metadata": {},
+   "source": [
```
[the remark this answers is not in the document]
Comment (eirikgr) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:13]: I agree. It is anyway incomplete.

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb (hunk 2 above)
[the remark this answers is not in the document]
Comment (eirikgr) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:187]: Ok, moved to using this. Works fine in newest commit.

[the remark this answers is not in the document]
Comment (marianaiv) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:187]: Then we don't need the commented lines here, right?

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb [hunk 4]
```diff
@@ -0,0 +1,1803 @@
...
+      "jupyter-events 0.7.0 requires jsonschema[format-nongpl]>=4.18.0, but you have jsonschema 4.9.1 which is incompatible.\n",
+      "voila 0.5.5 requires jupyter-server<3,>=2.0.0, but you have jupyter-server 1.10.2 which is incompatible.\n",
+      "voila 0.5.5 requires nbconvert<8,>=6.4.5, but you have nbconvert 6.4.0 which is incompatible.\n"
+     ]
+    }
+   ],
+   "source": [
+    "!pip install atlasopenmagic==0.4.0\n",
+    "from atlasopenmagic import install_from_environment\n",
+    "install_from_environment()"
```
Comment (marianaiv) [inline 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:495]: This should go before importing. Maybe where the commented lines with pip install are?

Comment (marianaiv) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:495]: I am being picky here but I would also say: run everything but this installation cell, because the output is gigantic and a bit annoying when looking at the notebook. Maybe delete the output before saving?

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb [hunk 5]
```diff
@@ -0,0 +1,1803 @@
...
+    "        'list' : [atom.get_urls('345060',skim)[0], #'345060.PowhegPythia8EvtGen_NNLOPS_nnlo_30_ggH125_ZZ4l.exactly4lep',\n",
+    "                  atom.get_urls('346228',skim)[0], #'346228.PowhegPy8EG_NNPDF30_AZNLOCTEQ6L1_VBFH125_ZZ4lep_notau.exactly4lep',\n",
+    "                  atom.get_urls('346311',skim)[0], #'346311.PowhegPythia8EvtGen_NNPDF30_AZNLO_WpH125J_Wincl_H_incl_MINLO.exactly4lep',\n",
+    "                  atom.get_urls('346312',skim)[0], #'346312.PowhegPythia8EvtGen_NNPDF30_AZNLO_WmH125J_Wincl_H_incl_MINLO.exactly4lep',\n",
+    "                  atom.get_urls('346340',skim)[0], #'346340.PowhegPy8EG_A14NNPDF23_NNPDF30ME_ttH125_ZZ4l_allhad.exactly4lep',\n",
+    "                  atom.get_urls('346341',skim)[0], #'346341.PowhegPy8EG_A14NNPDF23_NNPDF30ME_ttH125_ZZ4l_semilep.exactly4lep',\n",
+    "                  atom.get_urls('346342',skim)[0], #'346342.PowhegPy8EG_A14NNPDF23_NNPDF30ME_ttH125_ZZ4l_dilep.exactly4lep'          \n",
+    "                ],\n",
+    "        'color' : \"#00cdff\" # light blue\n",
+    "    },\n",
```
Comment (marianaiv) [inline 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:618]: I am sorry that you already wrote this and now I added a helper for this in atlasopenmagic. To make it easier in the future to put together dataset this is the new approach:
```
import atlasopenmagic as atom
mc_defs = {
    r'Background $t\bar t$':    {'dids': [410470],                      'color': 'yellow'},
    r'Background $V+$jets':     {'dids': [700335,700336,700337],        'color': 'orange'},
    r'Background Diboson':      {'dids': [700488,700489,700490,700491],'color': 'green'},
    r'Background $ZZ^{*}$':     {'dids': [700600,700601],               'color': '#ff0000'},
    r'Signal ($m_H$=125 GeV)':  {'dids': [345060,346228],              'color': '#00cdff'},
}

mc_samples   = atom.build_mc_dataset(mc_defs,   skim='2bjets', protocol='https')
data_samples = atom.build_data_dataset('2bjets',  color='red', protocol='https')

samples = {**data_samples, **mc_samples}
```

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb [hunk 6]
```diff
@@ -0,0 +1,1803 @@
...
+      "value = 'root://eospublic.cern.ch//eos/opendata/atlas/rucio/opendata/ODEO_FEB2025_v0_exactly4lep_data15_periodD.exactly4lep.root'\n"
+     ]
+    }
+   ],
+   "source": [
+    "# Print the samples dict for the key 'data'\n",
+    "print(samples['data'])\n",
```
Comment (marianaiv) [inline 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:649]: I would avoid printing the dict here

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb [hunk 7]
```diff
@@ -0,0 +1,1803 @@
...
+     ]
+    }
+   ],
+   "source": [
+    "# We open an MC data file with sample value \"Zee\" using samples and infofile for reference of filenames\n",
+    "print(samples[r'Background $Z,t\\bar{t},t\\bar{t}+V,VVV$'])\n",
```
Comment (marianaiv) [inline 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:1084]: I would also avoid printing the dictionary here

**Review by marianaiv — CHANGES_REQUESTED** [review]
Thanks @eirikgr! A couple of picky comments, and most importantly a change in the way to retrieve the URLs

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb (hunk 5 above)
Comment (eirikgr) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:618]: Ok, great. Much better :-). However, the `build_mc_dataset` function does not seem to exist in atlasopenmagic 0.4.0

> AttributeError: module 'atlasopenmagic' has no attribute 'build_mc_dataset'

Comment (marianaiv) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:618]: Oh yes, is on the new 0.5.0 version

Comment (zlmarshall) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:618]: It should be there in 0.5.0?

Comment (eirikgr) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:618]: Didn't realize a new version had been put out during the last few hours :-). Works in 0.5.0!

Comment (zlmarshall) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb:618]: Things move fast in the Thunderdome ;)

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb (hunk 4 above)
Comment (eirikgr) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb]: Yes, I've moved the content and removed the output from this cell in the latest commit

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb (hunk 7 above)
Comment (eirikgr) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb]: Fixes

File: 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb (hunk 6 above)
Comment (eirikgr) [reply 13-TeV-examples/uproot_python/HZZAnalysisNew.ipynb]: Fixed

**Review by zlmarshall — APPROVED** [review]
From my PoV this is now good to go. You've got a couple of threads with Mariana to finish up, but otherwise this is looking great. Thanks for putting it together, it's going to be a very useful example for the others to work from!

**Review by marianaiv — APPROVED** [review]
Good to go :)

**Comment by eirikgr** [comment]
Good. Thanks for useful comments and for developing the atlasopenmagic package! I see that one of the checks started failing. It seems to be related to the atlasopenmagic 

> ImportError                               Traceback (most recent call last)
Cell In[1], line 4
      2 import os.path
      3 get_ipython().system('pip install atlasopenmagic')
----> 4 from atlasopenmagic import install_from_environment
      5 install_from_environment()

> ImportError: cannot import name 'install_from_environment' from 'atlasopenmagic' (/opt/conda/lib/python3.11/site-packages/atlasopenmagic/__init__.py)

**Comment by marianaiv** [comment]
> Good. Thanks for useful comments and for developing the atlasopenmagic package! I see that one of the checks started failing. It seems to be related to the atlasopenmagic
> 
> > ImportError                               Traceback (most recent call last)
> > Cell In[1], line 4
> > 2 import os.path
> > 3 get_ipython().system('pip install atlasopenmagic')
> > ----> 4 from atlasopenmagic import install_from_environment
> > 5 install_from_environment()
> 
> > ImportError: cannot import name 'install_from_environment' from 'atlasopenmagic' (/opt/conda/lib/python3.11/site-packages/atlasopenmagic/**init**.py)

Yes, something to fix later
